name: Build and publish DockerVolumeBackup updates
on: [push, pull_request]

jobs:
  build:
    name: Build action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/docker/cli@master
        args: "build ."
